POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title" : "Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes" : 5
}
